pipeline {
	agent any
	stages {
		stage('Clean stage') {
			steps {
				dir("StockPricesApp") {
					bat 'mvn clean'
				}
			}
		}
		stage('Compile stage') {
			steps {
				dir("StockPricesApp") {
					bat 'mvn compile'
				}
			}
		}
		stage('Install stage') {
			steps {
				dir("StockPricesApp") {
					bat 'mvn install'
				}
			}
		}
		stage('Deploy stage') {
			steps {
				dir("StockPricesApp/target") {
					withEnv(['JENKINS_NODE_COOKIE=DontKillMe']) {
						bat 'start java -Dserver.port=3000 -jar StockPricesApp-0.0.1-SNAPSHOT.jar'
					}
				}
			}
		}
		stage('Docker') {
            steps {
                dir("StockPricesApp") {
                    bat 'docker build -t komallokhande123/stockapp.'    
                    bat 'docker run -d -p 9999:8080 --name stockapp_container komallokhande123/stockapp'
                }
            }
        }
	}
}
